export const POSTS_SUCCESS = 'POSTS_SUCCESS';
export const POSTS_FAIL = 'POSTS_FAIL';
export const POST_DETAILS_SUCCESS = 'POST_DETAILS_SUCCESS';
export const POST_DETAILS_FAIL = 'POST_DETAILS_FAIL';
export const POSTS_UPDATE_LIKE_SUCCESS = 'POSTS_UPDATE_LIKE_SUCCESS';
export const UPDATE_LIKE_SUCCESS = 'UPDATE_LIKE_SUCCESS';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
