export const PROFILE_BEGIN = 'PROFILE_BEGIN';
export const PROFILE_END = 'PROFILE_END';
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS';
export const PROFILES_SUCCESS = 'PROFILES_SUCCESS';
export const REPOS_SUCCESS = 'REPOS_SUCCESS';
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL';
export const PROFILES_FAIL = 'PROFILES_FAIL';
export const REPOS_FAIL = 'REPOS_FAIL';
