export const LOADING_FORM_START = 'LOADING_FORM_START';
export const LOADING_FORM_END = 'LOADING_FORM_END';
export const LOADING_PAGE_START = 'LOADING_PAGE_START';
export const LOADING_PAGE_END = 'LOADING_PAGE_END';
export const GET_CURRENT_PAGE = 'GET_CURRENT_PAGE';
